const {Reintegro} = require('./db/models');
const { notify } = require('./routes/auth.route');


const crearReintegros = async () => {
    await Reintegro.bulkCreate([
        {
            fecha_prestacion: '2025-10-15',
            integranteId: 1,
            medico: 'dr alejandro ruiz',
            especialidad: 'Cardiología',
            lugar: 'Hospital Central',
            factura_fecha: '2025-10-16',
            factura_cuit: '20-12345678-9',
            factura_valor: 85000.00,
            factura_persona: 'Juan Pérez',
            forma_pago: 'transferencia',
            cbu: '0000003100012345678901',
            observaciones: 'Angioplastia con stent coronario',
        },
        {
            fecha_prestacion: '2025-10-20',
            integranteId: 2,
            medico: 'dr cecilia lopez',
            especialidad: 'Medica Clinica',
            lugar: 'Clínica Santa María',
            factura_fecha: '2025-10-21',
            factura_cuit: '27-98765432-1',
            factura_valor: 45000.00,
            factura_persona: 'María Perez',
            forma_pago: 'efectivo',
            observaciones: 'Control post biopsia',
            estado: 'en analisis',
            usuarioUltimoCambio: 2
        },
        {
            fecha_prestacion: '2025-10-25',
            integranteId: 3,
            medico: 'dr alejandro ruiz',
            especialidad: 'Gastroenterología',
            lugar: 'Hospital Central',
            factura_fecha: '2025-10-26',
            factura_cuit: '23-11223344-5',
            factura_valor: 60000.00,
            factura_persona: 'Luciano Perez',
            forma_pago: 'cheque',
            observaciones: 'Evaluación postoperatoria',
            estado: 'rechazado',
            motivo: 'Factura incompleta',
            fecha_finalizacion: new Date(),
            usuarioUltimoCambio: 1
        },
        {   fecha_prestacion: '2025-10-18',
            integranteId: 2,
            medico: 'dr cecilia lopez',
            especialidad: 'Medica Clinica',
            lugar: 'Hospital Central',
            factura_fecha: '2025-10-19',
            factura_cuit: '20-12345678-9',
            factura_valor: 72000.00,
            factura_persona: 'Maria Perez',
            forma_pago: 'efectivo',
            cbu: null,
            observaciones: 'Crioterapia por verrugas',
            estado: 'en analisis',
            usuarioUltimoCambio: 2
        },
        {
            fecha_prestacion: '2025-10-20',
            integranteId: 3,
            medico: 'dr alejandro ruiz',
            especialidad: 'Cardiología',
            lugar: 'Clínica del Corazón',
            factura_fecha: '2025-10-21',
            factura_cuit: '23-11223344-5',
            factura_valor: 95000.00,
            factura_persona: 'Luciano Perez',
            forma_pago: 'cheque',
            cbu: null,
            observaciones: 'Holter 24 hs por arritmia ventricular',
            estado: 'en analisis',
            usuarioUltimoCambio: 1
        },
        {
            fecha_prestacion: '2025-10-22',
            integranteId: 4,
            medico: 'dr alejandro ruiz',
            especialidad: 'Traumatología',
            lugar: 'Hospital Central',
            factura_fecha: '2025-10-23',
            factura_cuit: '20-12345678-9',
            factura_valor: 68000.00,
            factura_persona: 'Sofia Perez',
            forma_pago: 'transferencia',
            cbu: '0000003100098765432101',
            observaciones: 'Colocación de yeso en muñeca izquierda por fractura ',
            estado: 'observado',
            fecha_finalizacion: '2025-11-05', //Fecha de cuando se cambio el estado
            motivo: 'Falta radiografía',
            usuarioUltimoCambio: 5
        },
        {
            fecha_prestacion: '2025-10-24',
            integranteId: 5,
            medico: 'dr cecilia lopez',
            especialidad: 'Traumatología',
            lugar: 'Clínica Santa María',
            factura_fecha: '2025-10-25',
            factura_cuit: '27-98765432-1',
            factura_valor: 54000.00,
            factura_persona: 'Carlos Perez',
            forma_pago: 'efectivo',
            cbu: null,
            observaciones: 'Resonancia magnética de rodilla derecha',
            estado: 'observado',
            fecha_finalizacion: '2025-10-26', //Fecha de cuando se cambio el estado
            motivo: 'Falta firma del profesional',
            usuarioUltimoCambio: 2
        },
        {
            fecha_prestacion: '2025-10-26',
            integranteId: 6,
            medico: 'dr cecilia lopez',
            especialidad: 'Medica Clinica',
            lugar: 'Hospital Central',
            factura_fecha: '2025-10-27',
            factura_cuit: '20-12345678-9',
            factura_valor: 61000.00,
            factura_persona: 'Ana Perez',
            forma_pago: 'transferencia',
            cbu: '0000003100011122233344',
            observaciones: 'Prueba de alergia por sospecha de urticaria grave',
            estado: 'observado',
            fecha_finalizacion: '2025-10-31', //Fecha de cuando se cambio el estado
            motivo: 'Estudios adjuntos ilegibles',
            usuarioUltimoCambio: 2
        },
        {
            fecha_prestacion: '2025-10-28',
            integranteId: 7,
            medico: 'dr alejandro ruiz',
            especialidad: 'Cardiología',
            lugar: 'Clínica del Corazón',
            factura_fecha: '2025-10-29',
            factura_cuit: '23-11223344-5',
            factura_valor: 88000.00,
            factura_persona: 'Matias Lopez',
            forma_pago: 'cheque',
            cbu: null,
            observaciones: 'Consulta por palpitaciones frecuentes',
            estado: 'rechazado',
            motivo: 'Factura vencida',
            fecha_finalizacion: new Date(),
            usuarioUltimoCambio: 1
        },
        {
            fecha_prestacion: '2025-10-30',
            integranteId: 8,
            medico: 'dr cecilia lopez',
            especialidad: 'Medica Clinica',
            lugar: 'Hospital Central',
            factura_fecha: '2025-10-31',
            factura_cuit: '20-12345678-9',
            factura_valor: 70000.00,
            factura_persona: 'Pedro Lopez',
            forma_pago: 'transferencia',
            cbu: '0000003100099999888877',
            observaciones: 'Consulta medica por asma leve',
            estado: 'rechazado',
            motivo: 'Falta autorización previa',
            fecha_finalizacion: new Date(),
            usuarioUltimoCambio: 2
        },

        {
            fecha_prestacion: '2025-11-01',
            integranteId: 9,
            medico: 'clinica santa maria',
            especialidad: 'Neurología',
            lugar: 'Clínica Santa María',
            factura_fecha: '2025-11-02',
            factura_cuit: '27-98765432-1',
            factura_valor: 56000.00,
            factura_persona: 'Lucía Lopez',
            forma_pago: 'efectivo',
            cbu: null,
            observaciones: 'Estudio de tomografía computada con contraste ',
        },
        {
            fecha_prestacion: '2025-11-03',
            integranteId: 10,
            medico: 'clinica santa maria',
            especialidad: 'Gastroenterología',
            lugar: 'clinica santa maria',
            factura_fecha: '2025-11-04',
            factura_cuit: '20-12345678-9',
            factura_valor: 60000.00,
            factura_persona: 'Tomas Lopez',
            forma_pago: 'transferencia',
            cbu: '0000003100012345678901',
            observaciones: 'Prueba de tolerancia oral a la glucosa por sospecha de diabetes'
        },
        {
            fecha_prestacion: '2025-11-04',
            integranteId: 3,
            medico: 'dr alejandro ruiz',
            especialidad: 'Cardiología',
            lugar: 'Clínica del Corazón',
            factura_fecha: '2025-11-05',
            factura_cuit: '23-11223344-5',
            factura_valor: 92000.00,
            factura_persona: 'Luciano Perez',
            forma_pago: 'cheque',
            cbu: null,
            observaciones: 'Ecocardiograma de control post cirugía valvular',
            estado: 'aprobado',
            fecha_finalizacion: new Date(),
            usuarioUltimoCambio: 1
        },
        {
            fecha_prestacion: '2025-11-06',
            integranteId: 4,
            medico: 'dr cecilia lopez',
            especialidad: 'Neurología',
            lugar: 'clinica santa maria',
            factura_fecha: '2025-11-07',
            factura_cuit: '20-12345678-9',
            factura_valor: 81000.00,
            factura_persona: 'Sofia Perez',
            forma_pago: 'transferencia',
            cbu: '0000003100044444555566',
            observaciones: '- Electroencefalograma por episodios de pérdida de conciencia',
            estado: 'aprobado',
            fecha_finalizacion: new Date(),
            usuarioUltimoCambio: 2
        },
        {
            fecha_prestacion: '2025-11-08',
            integranteId: 6,
            medico: 'dr alejandro ruiz',
            especialidad: 'Cardiología',
            lugar: 'Hospital Central',
            factura_fecha: '2025-11-09',
            factura_cuit: '27-98765432-1',
            factura_valor: 73000.00,
            factura_persona: 'Ana Lopez ',
            forma_pago: 'efectivo',
            cbu: null,
            observaciones: 'Control post angioplastia con buena evolución',
            estado: 'aprobado',
            fecha_finalizacion: new Date(),
            usuarioUltimoCambio: 1
        },
        {
            fecha_prestacion: '2025-11-02',
            integranteId: 12,
            medico: 'dr alejandro ruiz',
            especialidad: 'Cardiología',
            lugar: 'Clínica Santa María',
            factura_fecha: '2025-11-03',
            factura_cuit: '20-44556677-3',
            factura_valor: 56000.00,
            factura_persona: 'María Gómez',
            forma_pago: 'transferencia',
            cbu: '0000003100098765432101',
            observaciones: 'Eco Doppler cardíaco + control',
            estado: 'aprobado',
            fecha_finalizacion: new Date(),
            usuarioUltimoCambio: 1
        },
        {
            fecha_prestacion: '2025-10-28',
            integranteId: 25,
            medico: 'dr cecilia lopez',
            especialidad: 'Clínica',
            lugar: 'Hospital Central',
            factura_fecha: '2025-10-29',
            factura_cuit: '27-99887766-5',
            factura_valor: 18000.00,
            factura_persona: 'Luis Herrera',
            forma_pago: 'efectivo',
            cbu: null,
            observaciones: 'Consulta clínica y laboratorios básicos',
            estado: 'recibido',
            motivo: null,
            fecha_finalizacion: null,
            usuarioUltimoCambio: null
        },
        {
            fecha_prestacion: '2025-11-12',
            integranteId: 7,
            medico: 'dr alejandro ruiz',
            especialidad: 'Cardiología',
            lugar: 'Instituto Cardiovascular Norte',
            factura_fecha: '2025-11-12',
            factura_cuit: '23-55443322-8',
            factura_valor: 124000.00,
            factura_persona: 'Ricardo Martínez',
            forma_pago: 'cheque',
            cbu: null,
            observaciones: 'Estudio Holter 24h + ergometría',
            estado: 'rechazado',
            motivo: 'Factura sin detalle de prácticas',
            fecha_finalizacion: new Date(),
            usuarioUltimoCambio: 1
        },
        {
            fecha_prestacion: '2025-09-30',
            integranteId: 34,
            medico: 'dr cecilia lopez',
            especialidad: 'Clínica',
            lugar: 'Sanatorio San José',
            factura_fecha: '2025-10-01',
            factura_cuit: '20-11223344-6',
            factura_valor: 32000.00,
            factura_persona: 'Paula Díaz',
            forma_pago: 'transferencia',
            cbu: '0000003100087654321123',
            observaciones: 'Internación de 24h por gastroenteritis',
            estado: 'observado',
            motivo: 'Falta comprobante de pago',
            fecha_finalizacion: new Date(),
            usuarioUltimoCambio: 2
        },
        {
            fecha_prestacion: '2025-11-20',
            integranteId: 3,
            medico: 'dr alejandro ruiz',
            especialidad: 'Cardiología',
            lugar: 'Hospital Central',
            factura_fecha: '2025-11-21',
            factura_cuit: '20-33221144-9',
            factura_valor: 47000.00,
            factura_persona: 'Gustavo López',
            forma_pago: 'efectivo',
            cbu: null,
            observaciones: 'Control post angioplastia',
            estado: 'aprobado',
            fecha_finalizacion: new Date(),
            usuarioUltimoCambio: 1
        },
        {
            fecha_prestacion: '2025-10-05',
            integranteId: 18,
            medico: 'dr cecilia lopez',
            especialidad: 'Clínica',
            lugar: 'Clínica Los Andes',
            factura_fecha: '2025-10-06',
            factura_cuit: '27-55667788-0',
            factura_valor: 15500.00,
            factura_persona: 'Romina Sosa',
            forma_pago: 'transferencia',
            cbu: '0000003100011111111109',
            observaciones: 'Consulta clínica con estudios complementarios',
            estado: 'rechazado',
            motivo: 'Especialidad no coincide con la práctica facturada',
            fecha_finalizacion: new Date(),
            usuarioUltimoCambio: 2
        },
        {
            fecha_prestacion: '2025-11-08',
            integranteId: 46,
            medico: 'dr alejandro ruiz',
            especialidad: 'Cardiología',
            lugar: 'Instituto Cardiológico del Sur',
            factura_fecha: '2025-11-09',
            factura_cuit: '23-66778855-4',
            factura_valor: 96000.00,
            factura_persona: 'Diego Fernández',
            forma_pago: 'efectivo',
            cbu: null,
            observaciones: 'Cateterismo diagnóstico',
            estado: 'en analisis',
            motivo: null,
            fecha_finalizacion: null,
            usuarioUltimoCambio: 1
        },
        {
            fecha_prestacion: '2025-09-22',
            integranteId: 9,
            medico: 'dr cecilia lopez',
            especialidad: 'Clínica',
            lugar: 'Hospital Central',
            factura_fecha: '2025-09-23',
            factura_cuit: '20-90909090-1',
            factura_valor: 21000.00,
            factura_persona: 'Elena Torres',
            forma_pago: 'cheque',
            cbu: null,
            observaciones: 'Control clínico + medicación de soporte',
            estado: 'aprobado',
            fecha_finalizacion: new Date(),
            usuarioUltimoCambio: 5
        },
        {
            fecha_prestacion: '2025-11-18',
            integranteId: 22,
            medico: 'dr alejandro ruiz',
            especialidad: 'Cardiología',
            lugar: 'Clínica Santa María',
            factura_fecha: '2025-11-19',
            factura_cuit: '27-12349876-4',
            factura_valor: 52000.00,
            factura_persona: 'Natalia Cabrera',
            forma_pago: 'transferencia',
            cbu: '0000003100022222222209',
            observaciones: 'Ergometría + consulta especializada',
            estado: 'observado',
            motivo: 'Se solicita historia clínica adjunta',
            fecha_finalizacion: new Date(),
            usuarioUltimoCambio: 1
        },
        {
            fecha_prestacion: '2025-10-30',
            integranteId: 50,
            medico: 'dr cecilia lopez',
            especialidad: 'Clínica',
            lugar: 'Sanatorio Sur',
            factura_fecha: '2025-10-31',
            factura_cuit: '23-44559900-2',
            factura_valor: 39000.00,
            factura_persona: 'Tomás Rivas',
            forma_pago: 'efectivo',
            cbu: null,
            observaciones: 'Atención por infección urinaria',
            estado: 'recibido',
            motivo: null,
            fecha_finalizacion: null,
            usuarioUltimoCambio: null
        },
        {
            fecha_prestacion: '2025-09-12',
            integranteId: 2,
            medico: 'dr marcelo aguirre',
            especialidad: 'clinica',
            lugar: 'Centro Médico Los Robles',
            factura_fecha: '2025-09-13',
            factura_cuit: '20-33445566-9',
            factura_valor: 42000.00,
            factura_persona: 'Lucía Benítez',
            forma_pago: 'efectivo',
            observaciones: 'Consulta clínica general'
        },
        {
            fecha_prestacion: '2025-08-04',
            integranteId: 3,
            medico: 'dra veronica salinas',
            especialidad: 'pediatria',
            lugar: 'Centro Médico Los Robles',
            factura_fecha: '2025-08-05',
            factura_cuit: '27-98765432-1',
            factura_valor: 35000.00,
            factura_persona: 'Mariana Rivas',
            forma_pago: 'transferencia',
            cbu: '0000003100011122233344',
            observaciones: 'Control pediátrico'
        },
        {
            fecha_prestacion: '2025-07-20',
            integranteId: 5,
            medico: 'dr julio romero',
            especialidad: 'traumatologia',
            lugar: 'Clínica Nuestra Señora del Pilar',
            factura_fecha: '2025-07-21',
            factura_cuit: '23-44556677-0',
            factura_valor: 115000.00,
            factura_persona: 'Carlos López',
            forma_pago: 'cheque',
            observaciones: 'Placa de tobillo'
        },
        {
            fecha_prestacion: '2025-06-15',
            integranteId: 7,
            medico: 'dra lorena torres',
            especialidad: 'cardiologia',
            lugar: 'Clínica Santa María',
            factura_fecha: '2025-06-16',
            factura_cuit: '20-12344321-5',
            factura_valor: 99000.00,
            factura_persona: 'Raúl Medina',
            forma_pago: 'transferencia',
            cbu: '0000003100099988877766',
            observaciones: 'Holter 24 hs'
        },
        {
            fecha_prestacion: '2025-05-02',
            integranteId: 4,
            medico: 'dr adrian castro',
            especialidad: 'clinica',
            lugar: 'Clínica Santa María',
            factura_fecha: '2025-05-03',
            factura_cuit: '20-11221122-3',
            factura_valor: 28000.00,
            factura_persona: 'Belén Arrieta',
            forma_pago: 'efectivo'
        },
        {
            fecha_prestacion: '2025-04-10',
            integranteId: 6,
            medico: 'dr nicolas sosa',
            especialidad: 'dermatologia',
            lugar: 'Centro Médico Los Robles',
            factura_fecha: '2025-04-11',
            factura_cuit: '27-55443322-9',
            factura_valor: 36000.00,
            factura_persona: 'Esteban Rivas',
            forma_pago: 'transferencia',
            cbu: '0000003100022222223333',
            observaciones: 'Tratamiento para dermatitis'
        },
        {
            fecha_prestacion: '2025-03-18',
            integranteId: 8,
            medico: 'dra monica vera',
            especialidad: 'ginecologia',
            lugar: 'Clínica Nuestra Señora del Pilar',
            factura_fecha: '2025-03-19',
            factura_cuit: '23-76543210-6',
            factura_valor: 74000.00,
            factura_persona: 'Romina Cuello',
            forma_pago: 'efectivo'
        },
        {
            fecha_prestacion: '2025-02-25',
            integranteId: 9,
            medico: 'dr leonel quiroga',
            especialidad: 'neurologia',
            lugar: 'Clínica Santa María',
            factura_fecha: '2025-02-26',
            factura_cuit: '20-90807060-4',
            factura_valor: 132000.00,
            factura_persona: 'Andrés Molina',
            forma_pago: 'transferencia',
            cbu: '0000003100044455566677',
            observaciones: 'Electromiografía'
        },
        {
            fecha_prestacion: '2025-01-11',
            integranteId: 10,
            medico: 'dra paula mendes',
            especialidad: 'clinica',
            lugar: 'Centro Médico Los Robles',
            factura_fecha: '2025-01-12',
            factura_cuit: '27-10101010-1',
            factura_valor: 31000.00,
            factura_persona: 'Soledad Díaz',
            forma_pago: 'cheque'
        },
        {
            fecha_prestacion: '2025-10-02',
            integranteId: 4,
            medico: 'dr gustavo rios',
            especialidad: 'pediatria',
            lugar: 'Clínica Santa María',
            factura_fecha: '2025-10-03',
            factura_cuit: '20-22223333-8',
            factura_valor: 39000.00,
            factura_persona: 'Rocío Blanco',
            forma_pago: 'transferencia',
            cbu: '0000003100066666667777'
        },
        {
            fecha_prestacion: '2025-09-27',
            integranteId: 1,
            medico: 'dr enrique godoy',
            especialidad: 'pediatria',
            lugar: 'Centro Médico Los Robles',
            factura_fecha: '2025-09-28',
            factura_cuit: '27-99998888-2',
            factura_valor: 33000.00,
            factura_persona: 'Melina Duarte',
            forma_pago: 'efectivo'
        },
        {
            fecha_prestacion: '2025-11-05',
            integranteId: 6,
            medico: 'dra natalia peralta',
            especialidad: 'clinica',
            lugar: 'Clínica Santa María',
            factura_fecha: '2025-11-06',
            factura_cuit: '20-55667788-5',
            factura_valor: 44000.00,
            factura_persona: 'Gustavo Herrera',
            forma_pago: 'transferencia',
            cbu: '0000003100012345678901'
        },
        {
            fecha_prestacion: '2025-08-09',
            integranteId: 12,
            medico: 'dr walter morales',
            especialidad: 'cardiologia',
            lugar: 'Clínica Santa María',
            factura_fecha: '2025-08-10',
            factura_cuit: '23-44559977-3',
            factura_valor: 125000.00,
            factura_persona: 'Héctor Silva',
            forma_pago: 'efectivo',
            observaciones: 'Ergometría'
        },
        {
            fecha_prestacion: '2025-07-29',
            integranteId: 3,
            medico: 'dra jimena farías',
            especialidad: 'dermatologia',
            lugar: 'Clínica Nuestra Señora del Pilar',
            factura_fecha: '2025-07-30',
            factura_cuit: '27-30303030-9',
            factura_valor: 27000.00,
            factura_persona: 'Valeria Juárez',
            forma_pago: 'cheque'
        },
        {
            fecha_prestacion: '2025-06-07',
            integranteId: 11,
            medico: 'dr federico luna',
            especialidad: 'neurologia',
            lugar: 'Centro Médico Los Robles',
            factura_fecha: '2025-06-08',
            factura_cuit: '20-12121212-7',
            factura_valor: 148000.00,
            factura_persona: 'Jorge Ledesma',
            forma_pago: 'transferencia',
            cbu: '0000003100088888889999',
            observaciones: 'Resonancia magnética'
        },
        {
            fecha_prestacion: '2025-10-22',
            integranteId: 1,
            medico: 'dr alejandro ruiz',
            especialidad: 'cardiologia',
            lugar: 'Hospital Central',
            factura_fecha: '2025-10-23',
            factura_cuit: '20-12345678-9',
            factura_valor: 78000.00,
            factura_persona: 'Juan Pérez',
            forma_pago: 'transferencia',
            cbu: '0000003100012345678901',
            observaciones: 'Control post angioplastia',
            estado: 'recibido'
        },
        {
            fecha_prestacion: '2025-09-14',
            integranteId: 3,
            medico: 'dr alejandro ruiz',
            especialidad: 'cardiologia',
            lugar: 'Hospital Central',
            factura_fecha: '2025-09-15',
            factura_cuit: '27-55443322-1',
            factura_valor: 54000.00,
            factura_persona: 'Laura Medina',
            forma_pago: 'efectivo',
            estado: 'en analisis',
            usuarioUltimoCambio: 1
        },
        {
            fecha_prestacion: '2025-08-03',
            integranteId: 7,
            medico: 'dr alejandro ruiz',
            especialidad: 'cardiologia',
            lugar: 'Hospital Central',
            factura_fecha: '2025-08-04',
            factura_cuit: '23-99887766-4',
            factura_valor: 112000.00,
            factura_persona: 'Rodrigo Cáceres',
            forma_pago: 'transferencia',
            cbu: '0000003100022222223333',
            observaciones: 'Eco Doppler color',
            estado: 'recibido'
        },
        {
            fecha_prestacion: '2025-11-02',
            integranteId: 4,
            medico: 'dr alejandro ruiz',
            especialidad: 'cardiologia',
            lugar: 'Hospital Central',
            factura_fecha: '2025-11-03',
            factura_cuit: '20-66554433-8',
            factura_valor: 87000.00,
            factura_persona: 'Martina Ruiz',
            forma_pago: 'cheque',
            estado: 'en analisis',
            usuarioUltimoCambio: 1
        },
        {
            fecha_prestacion: '2025-07-18',
            integranteId: 9,
            medico: 'dr alejandro ruiz',
            especialidad: 'cardiologia',
            lugar: 'Hospital Central',
            factura_fecha: '2025-07-19',
            factura_cuit: '27-11112222-3',
            factura_valor: 44500.00,
            factura_persona: 'Gisela López',
            forma_pago: 'efectivo',
            estado: 'recibido'
        },
        {
            fecha_prestacion: '2025-06-29',
            integranteId: 2,
            medico: 'dr alejandro ruiz',
            especialidad: 'cardiologia',
            lugar: 'Hospital Central',
            factura_fecha: '2025-06-30',
            factura_cuit: '20-99334455-1',
            factura_valor: 72000.00,
            factura_persona: 'Daniel Cabrera',
            forma_pago: 'transferencia',
            cbu: '0000003100044445555666',
            estado: 'en analisis',
            usuarioUltimoCambio: 1
        },
        {
            fecha_prestacion: '2025-05-05',
            integranteId: 6,
            medico: 'dr alejandro ruiz',
            especialidad: 'cardiologia',
            lugar: 'Hospital Central',
            factura_fecha: '2025-05-06',
            factura_cuit: '20-22229999-0',
            factura_valor: 31000.00,
            factura_persona: 'Marta Quiroga',
            forma_pago: 'efectivo',
            observaciones: 'Electrocardiograma',
            estado: 'recibido'
        },
        {
            fecha_prestacion: '2025-04-11',
            integranteId: 10,
            medico: 'dr alejandro ruiz',
            especialidad: 'cardiologia',
            lugar: 'Hospital Central',
            factura_fecha: '2025-04-12',
            factura_cuit: '27-78787878-3',
            factura_valor: 59000.00,
            factura_persona: 'Luis Gutiérrez',
            forma_pago: 'cheque',
            estado: 'en analisis',
            usuarioUltimoCambio: 1
        },
        {
            fecha_prestacion: '2025-03-20',
            integranteId: 12,
            medico: 'dr alejandro ruiz',
            especialidad: 'cardiologia',
            lugar: 'Hospital Central',
            factura_fecha: '2025-03-21',
            factura_cuit: '20-30303030-9',
            factura_valor: 97000.00,
            factura_persona: 'Silvia Palacios',
            forma_pago: 'transferencia',
            cbu: '0000003100077778888999',
            estado: 'recibido'
        },
        {
            fecha_prestacion: '2025-02-14',
            integranteId: 5,
            medico: 'dr alejandro ruiz',
            especialidad: 'cardiologia',
            lugar: 'Hospital Central',
            factura_fecha: '2025-02-15',
            factura_cuit: '23-66665555-4',
            factura_valor: 68000.00,
            factura_persona: 'Mario Fernández',
            forma_pago: 'efectivo',
            observaciones: 'Consulta + laboratorio cardio',
            estado: 'en analisis',
            usuarioUltimoCambio: 1
        }


    ]);
 }

 module.exports = {crearReintegros};