const {Reintegro} = require('./db/models');
const { notify } = require('./routes/auth.route');


const crearReintegros = async () => {
    await Reintegro.bulkCreate([
        {
            fecha_prestacion: '2025-10-15',
            integranteId: 1,
            medico: 'dr alejandro ruiz',
            especialidad: 'Cardiología',
            lugar: 'Hospital Central',
            factura_fecha: '2025-10-16',
            factura_cuit: '20-12345678-9',
            factura_valor: 85000.00,
            factura_persona: 'Juan Pérez',
            forma_pago: 'transferencia',
            cbu: '0000003100012345678901',
            observaciones: 'Angioplastia con stent coronario',
        },
        {
            fecha_prestacion: '2025-10-20',
            integranteId: 2,
            medico: 'dr cecilia lopez',
            especialidad: 'Medica Clinica',
            lugar: 'Clínica Santa María',
            factura_fecha: '2025-10-21',
            factura_cuit: '27-98765432-1',
            factura_valor: 45000.00,
            factura_persona: 'María Perez',
            forma_pago: 'efectivo',
            observaciones: 'Control post biopsia',
            estado: 'en analisis',
            usuarioUltimoCambio: 2
        },
        {
            fecha_prestacion: '2025-10-25',
            integranteId: 3,
            medico: 'clinica santa maria',
            especialidad: 'Gastroenterología',
            lugar: 'Hospital Central',
            factura_fecha: '2025-10-26',
            factura_cuit: '23-11223344-5',
            factura_valor: 60000.00,
            factura_persona: 'Luciano Perez',
            forma_pago: 'cheque',
            observaciones: 'Evaluación postoperatoria',
            estado: 'rechazado',
            motivo: 'Factura incompleta',
            fecha_finalizacion: new Date(),
            usuarioUltimoCambio: 1
        },
        {   fecha_prestacion: '2025-10-18',
            integranteId: 2,
            medico: 'dr cecilia lopez',
            especialidad: 'Medica Clinica',
            lugar: 'Hospital Central',
            factura_fecha: '2025-10-19',
            factura_cuit: '20-12345678-9',
            factura_valor: 72000.00,
            factura_persona: 'Maria Perez',
            forma_pago: 'efectivo',
            cbu: null,
            observaciones: 'Crioterapia por verrugas',
            estado: 'en analisis',
            usuarioUltimoCambio: 2
        },
        {
            fecha_prestacion: '2025-10-20',
            integranteId: 3,
            medico: 'dr alejandro ruiz',
            especialidad: 'Cardiología',
            lugar: 'Clínica del Corazón',
            factura_fecha: '2025-10-21',
            factura_cuit: '23-11223344-5',
            factura_valor: 95000.00,
            factura_persona: 'Luciano Perez',
            forma_pago: 'cheque',
            cbu: null,
            observaciones: 'Holter 24 hs por arritmia ventricular',
            estado: 'en analisis',
            usuarioUltimoCambio: 1
        },
        {
            fecha_prestacion: '2025-10-22',
            integranteId: 4,
            medico: 'clinica santa maria',
            especialidad: 'Traumatología',
            lugar: 'Hospital Central',
            factura_fecha: '2025-10-23',
            factura_cuit: '20-12345678-9',
            factura_valor: 68000.00,
            factura_persona: 'Sofia Perez',
            forma_pago: 'transferencia',
            cbu: '0000003100098765432101',
            observaciones: 'Colocación de yeso en muñeca izquierda por fractura ',
            estado: 'observado',
            fecha_finalizacion: '2025-11-05', //Fecha de cuando se cambio el estado
            motivo: 'Falta radiografía',
            usuarioUltimoCambio: 2
        },
        {
            fecha_prestacion: '2025-10-24',
            integranteId: 5,
            medico: 'clinica santa maria',
            especialidad: 'Traumatología',
            lugar: 'Clínica Santa María',
            factura_fecha: '2025-10-25',
            factura_cuit: '27-98765432-1',
            factura_valor: 54000.00,
            factura_persona: 'Carlos Perez',
            forma_pago: 'efectivo',
            cbu: null,
            observaciones: 'Resonancia magnética de rodilla derecha',
            estado: 'observado',
            fecha_finalizacion: '2025-10-26', //Fecha de cuando se cambio el estado
            motivo: 'Falta firma del profesional',
            usuarioUltimoCambio: 3
        },
        {
            fecha_prestacion: '2025-10-26',
            integranteId: 6,
            medico: 'dr cecilia lopez ',
            especialidad: 'Medica Clinica',
            lugar: 'Hospital Central',
            factura_fecha: '2025-10-27',
            factura_cuit: '20-12345678-9',
            factura_valor: 61000.00,
            factura_persona: 'Ana Perez',
            forma_pago: 'transferencia',
            cbu: '0000003100011122233344',
            observaciones: 'Prueba de alergia por sospecha de urticaria grave',
            estado: 'observado',
            fecha_finalizacion: '2025-10-31', //Fecha de cuando se cambio el estado
            motivo: 'Estudios adjuntos ilegibles',
            usuarioUltimoCambio: 1
        },
        {
            fecha_prestacion: '2025-10-28',
            integranteId: 7,
            medico: 'dr alejandro ruiz',
            especialidad: 'Cardiología',
            lugar: 'Clínica del Corazón',
            factura_fecha: '2025-10-29',
            factura_cuit: '23-11223344-5',
            factura_valor: 88000.00,
            factura_persona: 'Matias Lopez',
            forma_pago: 'cheque',
            cbu: null,
            observaciones: 'Consulta por palpitaciones frecuentes',
            estado: 'rechazado',
            motivo: 'Factura vencida',
            fecha_finalizacion: new Date(),
            usuarioUltimoCambio: 2
        },
        {
            fecha_prestacion: '2025-10-30',
            integranteId: 8,
            medico: 'dr cecilia lopez',
            especialidad: 'Medica Clinica',
            lugar: 'Hospital Central',
            factura_fecha: '2025-10-31',
            factura_cuit: '20-12345678-9',
            factura_valor: 70000.00,
            factura_persona: 'Pedro Lopez',
            forma_pago: 'transferencia',
            cbu: '0000003100099999888877',
            observaciones: 'Consulta medica por asma leve',
            estado: 'rechazado',
            motivo: 'Falta autorización previa',
            fecha_finalizacion: new Date(),
            usuarioUltimoCambio: 3
        },

        {
            fecha_prestacion: '2025-11-01',
            integranteId: 9,
            medico: 'clinica santa maria',
            especialidad: 'Neurología',
            lugar: 'Clínica Santa María',
            factura_fecha: '2025-11-02',
            factura_cuit: '27-98765432-1',
            factura_valor: 56000.00,
            factura_persona: 'Lucía Lopez',
            forma_pago: 'efectivo',
            cbu: null,
            observaciones: 'Estudio de tomografía computada con contraste ',
        },
        {
            fecha_prestacion: '2025-11-03',
            integranteId: 10,
            medico: 'clinica santa maria',
            especialidad: 'Gastroenterología',
            lugar: 'clinica santa maria',
            factura_fecha: '2025-11-04',
            factura_cuit: '20-12345678-9',
            factura_valor: 60000.00,
            factura_persona: 'Tomas Lopez',
            forma_pago: 'transferencia',
            cbu: '0000003100012345678901',
            observaciones: 'Prueba de tolerancia oral a la glucosa por sospecha de diabetes'
        },
        {
            fecha_prestacion: '2025-11-04',
            integranteId: 3,
            medico: 'dr alejandro ruiz',
            especialidad: 'Cardiología',
            lugar: 'Clínica del Corazón',
            factura_fecha: '2025-11-05',
            factura_cuit: '23-11223344-5',
            factura_valor: 92000.00,
            factura_persona: 'Luciano Perez',
            forma_pago: 'cheque',
            cbu: null,
            observaciones: 'Ecocardiograma de control post cirugía valvular',
            estado: 'aprobado',
            fecha_finalizacion: new Date(),
            usuarioUltimoCambio: 1
        },
        {
            fecha_prestacion: '2025-11-06',
            integranteId: 4,
            medico: 'clinica santa maria',
            especialidad: 'Neurología',
            lugar: 'clinica santa maria',
            factura_fecha: '2025-11-07',
            factura_cuit: '20-12345678-9',
            factura_valor: 81000.00,
            factura_persona: 'Sofia Perez',
            forma_pago: 'transferencia',
            cbu: '0000003100044444555566',
            observaciones: '- Electroencefalograma por episodios de pérdida de conciencia',
            estado: 'aprobado',
            fecha_finalizacion: new Date(),
            usuarioUltimoCambio: 2
        },
        {
            fecha_prestacion: '2025-11-08',
            integranteId: 6,
            medico: 'dr alejandro ruiz',
            especialidad: 'Cardiología',
            lugar: 'Hospital Central',
            factura_fecha: '2025-11-09',
            factura_cuit: '27-98765432-1',
            factura_valor: 73000.00,
            factura_persona: 'Ana Lopez ',
            forma_pago: 'efectivo',
            cbu: null,
            observaciones: 'Control post angioplastia con buena evolución',
            estado: 'aprobado',
            fecha_finalizacion: new Date(),
            usuarioUltimoCambio: 3
        }

    ]);
 }

 module.exports = {crearReintegros};